name: Build & Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Ini WAJIB ditambahin kalau pakai WIF (tanpa JSON)
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    # Bagian ini yang diubah pakai 2 kode rahasia dari terminal tadi
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/418975844073/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-ac@project-aa571cb2-7559-4fff-9f6.iam.gserviceaccount.com'

    - uses: google-github-actions/setup-gcloud@v2

    - run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build & Push Image
      run: |
        IMAGE="asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/pso"
        docker build -t $IMAGE:$GITHUB_SHA .
        docker push $IMAGE:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        IMAGE="asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/pso"
        gcloud run deploy my-app-service \
          --image=$IMAGE:$GITHUB_SHA \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --port=8080 \
          --memory=512Mi \
          --set-env-vars="MONGODB_URL=${{ secrets.MONGODB_URL }}"